import Head from "next/head";
import Constellation from "../components/Constellation";
import fsPromises from "fs/promises";
import path from "path";

export default function Home({ constellations }) {
    return (
        <>
            <Head>
                <title>Stars Too Fondly</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
                <script
                    defer
                    data-domain="stars-too-fondly.netlify.app"
                    src="https://plausible.io/js/script.js"
                ></script>
            </Head>
            <header>
                <h1>Stars Too Fondly</h1>
                <h2>
                    Matching each constellation to a Dallas Stars player&apos;s
                    shot map.
                </h2>
                <p>
                    (
                    <a href="https://github.com/nguyenank/stars-too-fondly">
                        matching code
                    </a>{" "}
                    |{" "}
                    <a href="https://github.com/nguyenank/stars-too-fondly-site">
                        website code
                    </a>
                    )
                </p>
                <p>
                    Inspired by and implementation heavily drawn from Nebra Shot
                    Maps (
                    <a href="https://torvaney.github.io/projects/nebra/">
                        site
                    </a>{" "}
                    |{" "}
                    <a href="https://github.com/Torvaney/nebra-shot-maps">
                        code
                    </a>{" "}
                    |{" "}
                    <a href="https://www.youtube.com/watch?v=lHRcOQBDSKI&feature=youtu.be">
                        video
                    </a>
                    ) by Ben Torvaney.
                </p>
                <p>Last updated January 20th, 2023.</p>
                <hr />
            </header>
            <main>
                {constellations.map((constellation, i) => (
                    <Constellation key={i} constellation={constellation} />
                ))}
            </main>
        </>
    );
}

export async function getStaticProps() {
    const filePath = path.join(process.cwd(), "data/constellations.json");
    const jsonData = await fsPromises.readFile(filePath);
    const constellations = JSON.parse(jsonData);

    return {
        props: { constellations }
    };
}
